dataset:
    target: dataset.stage3.Stage3
    params:
      # Path to the file list.
      file_list: data_path/temp.list 

data_loader:
    batch_size: 2
    shuffle: true
    num_workers: 8
    drop_last: true

batch_transform:
    target: dataset.batch_transform.IdentityBatchTransform
